#!/bin/bash
set -e
force=
if [ -n "%1" -a "$1" = "--force" ]; then
	force=1
	shift
fi

test -d websolv || { echo "need to clone websolv first" >&2; false; }

cleanup()
{
	if [ -n "$version" ]; then
		echo "$version is incomplete"
		[ -e "$version/.download.log" ] && grep ERROR "$version/.download.log"
		rm -r "$version"/packages
	fi
}
trap cleanup EXIT
wantversion="$1"
URL="http://download.opensuse.org/history"
versions=($(curl --fail --silent $URL/list))
mkdir -p pool
for version in "${versions[@]}"; do
	[ -n "$wantversion" ] && [ "$version" != "$wantversion" ] && continue
	[ -z "$force" ] && [ -d "$version" ] && continue
	mkdir -p $version/packages
	websolv/Deptool.py -C "Tumbleweed-$version" parse small_bootable.t --metalink > $version/.packages.meta4
	while read file; do
		[ -e "pool/${file##*/}" ] || continue
		mkdir -p "$version/packages/${file%/*}"
		ln -f "pool/${file##*/}" "$version/packages/$file"
	done < <(sed -ne 's/.*file name="\([^"]\+\)".*/\1/p' $version/.packages.meta4)
	aria2c -q --continue -M $version/.packages.meta4 -d $version/packages -l "$version/.download.log" --log-level info
	du -sh $version
	while read file; do
		ln "$file" "pool/${file##*/}"
	done < <(find "$version" -type f -links 1 -name '*.rpm')
	[ -z "$wantversion" ] || break
done
unset version
