#!/bin/bash
set -e

name="${1:?}"
packages="${2:?}"
size="${3:-2G}"
osname="opensuse-tumbleweed"
arch='x86_64'
loop=
# XXX: create in /run
mp=$(mktemp -d -p /run -t mkimg.XXXXXXXXXX)
tmpmp=$(mktemp -d -p /run -t mkimg.XXXXXXXXXX)
layout='
label: gpt

size=100M, type=${uuid[esp]}
type=${uuid[root]}
'

#size=500M, type=${uuid[root]}
#type=${uuid[usr]}

declare -A uuid
init_uuids()
{
	while read -r n u; do
		[ "$n" = "NAME" ] && continue
		uuid[$n]=$u
	done < <(systemd-id128 show -u usr root esp swap)
}

cleanup()
{
	if [ -n "$mp" ]; then
		umount -R "$mp" || true
	fi
	if mountpoint -q "$tmpmp"; then
		umount -R "$tmpmp" || true
	fi
	if [ -n "$loop" ]; then
		losetup -d "$loop" || true
	fi
}
trap cleanup EXIT

init_uuids

eval layout="\"$layout\""

if [[ "${packages##*/}" =~ ^[0-9]+$ ]]; then
	rev="${packages##*/}"
fi

declare -A volume
volume[root]="root-$arch:$osname@1"
volume[usr]="usr-$arch:$osname@$rev"
volume[sysimage]="sysimage-$arch:$osname@$rev"
volume[var]="var-$osname"

dd if=/dev/zero of="$name" bs=1 seek="$size" count=0 status=none
loop=$(losetup --show -fP "$name")
echo "$layout" | sfdisk -q "$loop"

# EFI
mkfs.vfat "${loop}p1"

mkfs.btrfs -q "${loop}p2"
mount "${loop}p2" "$tmpmp"
btrfs subvolume create "$tmpmp/@auto/"
for v in root usr sysimage var; do # keep order
	btrfs subvolume create "$tmpmp/@auto/${volume[$v]}"
done
## XXX need this for now as long as systemd-dissect can't detect btrfs @auto volumes
btrfs subvolume set-default 257 "$tmpmp"
read -r rootdev rootuuid < <(findmnt -nvo "SOURCE,UUID" $tmpmp)
mount -o subvol="@auto/${volume[root]}" "$rootdev" "$mp"
# root fs layout
mkdir -p "$mp"/{etc,proc,sys,dev,var,tmp,run,usr,efi,mnt}
for i in bin sbin lib lib64; do
	ln -s usr/$i "$mp/$i"
done
mount "${loop}p1" "$mp/efi"
mount -o subvol="@auto/${volume[usr]}" "$rootdev" "$mp/usr"
mount -o subvol="@auto/${volume[var]}" "$rootdev" "$mp/var"
for i in tmp log/journal; do
	mkdir -p "$mp/var/$i"
done
for i in root home opt srv; do
	mkdir -p "$mp/var/$i"
	ln -s var/$i "$mp/$i"
done

## prepare separate usr tree
#mkfs.btrfs -q "${loop}p3"
#mount "${loop}p3" "$mp/usr"
#btrfs subvolume create "$mp/usr/@auto/"
#btrfs subvolume create "$mp/usr/@auto/$osname@$rev+3"
## XXX is it really always 257? :-)
#btrfs subvolume set-default 257 "$mp/usr"
#umount "$mp/usr"
#mount "${loop}p3" "$mp/usr"
#

mkdir -p "$mp/usr/lib/sysimage"
mount -o subvol="@auto/${volume[sysimage]}" "$rootdev" "$mp/usr/lib/sysimage"
# XXX: need to change to sysimage/packages
mkdir -p "$mp/usr/lib/sysimage/rpm-headers"
cp "$packages"/extents/* "$mp/usr/lib/sysimage/rpm-headers"
for i in "$mp/usr/lib/sysimage/rpm-headers"/*; do
	#echo "${i##*/}"
	echo -n .
	./busybox rpm --root "$mp" --force --only-prefix /usr --justfs -i "$i"
done
echo
mkdir -p "$mp/usr/local/bin"
cp busybox $mp/usr/local/bin/busybox
for i in wget rpm; do
	[ -e "$mp/usr/bin/$i" -o -L "$mp/usr/bin/$i" ] && continue
	ln -s busybox $mp/usr/local/bin/$i
done

### fstab

# XXX: use generator for that
cat > "$mp/etc/fstab" <<-EOF
UUID=$rootuuid /var btrfs subvol=@auto/${volume[var]}
UUID=$rootuuid /usr/lib/sysimage btrfs subvol=@auto/${volume[sysimage]}
EOF

### bootloader

ENTRY_TOKEN=Default
# XXX: use entry token for newer systemd
echo "MACHINE_ID=$ENTRY_TOKEN" > "$mp/usr/lib/kernel/install.conf"
#bootctl install --no-variables --install-source=image --make-entry-directory=yes --entry-token=os-id --root="$mp"
install -D -m 444 "$mp"/usr/lib/systemd/boot/efi/systemd-bootx64.efi "$mp/efi/EFI/BOOT/BOOTX64.EFI"
install -D -m 444 "$mp"/usr/lib/systemd/boot/efi/systemd-bootx64.efi "$mp/efi/EFI/systemd/systemd-bootx64.efi"
#
mkdir -p "$mp/efi/$ENTRY_TOKEN"
mkdir -p "$mp/efi/loader/entries"
for k in "$mp"/usr/lib/modules/*/vmlinuz; do
	kv="${k%/*}"
	kv="${kv##*/}"
	kf="/$ENTRY_TOKEN/$kv/linux"
	initrd="${kf%/*}/initrd"
	install -D -m 444 "$k" "$mp/efi$kf"
	cat > "$mp/efi/loader/entries/$ENTRY_TOKEN-$kv.conf" <<-EOF
	title       openSUSE Tumbleweed@rev
	version     $kv
	machine-id  $ENTRY_TOKEN
	sort-key    $osname
	options     root=UUID=$rootuuid rootflags=subvol=@auto/${volume[root]} mount.usr=UUID=$rootuuid mount.usrflags=subvol=@auto/${volume[usr]} console=tty0 console=ttyS0,115200 quiet
	linux       $kf
	initrd      $initrd
	EOF

	# XXX: should read deps from /var
	systemd-nspawn -q -D "$mp" depmod $kv
	systemd-nspawn -q -D "$mp" dracut -q \
		--no-hostonly \
		--no-hostonly-default-device \
		--no-hostonly-cmdline \
		--no-hostonly-default-device \
		-o 'plymouth i18n network kernel-modules kernel-modules-extra multipath' \
		-d btrfs \
		"/efi/$initrd" "$kv"
	systemd-nspawn -q -D "$mp" systemctl enable debug-shell.service
done
		#--add-drivers dmi-sysfs \
		#--force-drivers dmi-sysfs \

tree "$mp/efi"

# XXX
cat /etc/resolv.conf > "$mp/etc/resolv.conf"

# firstboot wizard doesn't like empty etc? seems to be read-only
: > "$mp/etc/machine-id"

mkdir -p "$mp/etc/systemd/network"
cat > "$mp/etc/systemd/network/80-dhcp.network" <<-EOF
[Match]
Name=en*

[Network]
DHCP=yes
EOF
mkdir -p "$mp/etc/systemd/system-preset/"
echo "enable systemd-networkd.service" > "$mp/etc/systemd/system-preset/50-networkd.preset"

cat >> "$mp/etc/fstab" <<-EOF
build-srcdir /mnt 9p trans=virtio,version=9p2000.L
EOF

cat > "$mp/root/.profile" <<-EOF
alias l='ls -al'
alias o='less'
EOF

btrfs prop set -t s "$mp/usr" ro true
