#!/bin/bash
set -e
test -d rpm2extents || { echo "need to clone rpm2extents first"; false; }
versions="$@"
if [ -z "$versions" ]; then
	versions=(data/*/packages)
	versions=("${versions[@]%/*}")
	versions=("${versions[@]##*/}")
fi
mkdir -p data/pool/extents
for version in "${versions[@]}"; do
	test -d "data/$version/packages" || continue
	mkdir -p "data/$version/extents"
	while read file; do
		[ -e "data/pool/extents/${file##*/}" ] || rpm2extents/rpm2extents.py "$file" > "data/pool/extents/${file##*/}"
		name=$(rpm -qp --qf '%{name}' "$file")
		[ -e "data/$version/extents/${name}.rpm" ] && continue
		ln data/pool/extents/${file##*/} "data/$version/extents/${name}.rpm"
		echo "$name" >> "data/$version/list"
	done < <(find "data/$version/packages" -name '*.rpm')
done
