#!/bin/bash
img="${1:?}"
shift
exec qemu-system-x86_64 -enable-kvm \
	-device virtio-blk,drive=hd1 \
	-drive file="$img",cache=unsafe,if=none,id=hd1 \
	-machine type=q35,accel=kvm \
	-object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0 \
	-smp 2 \
	-m 1024 -bios /usr/share/qemu/ovmf-x86_64.bin -M q35 \
	-chardev stdio,mux=on,signal=off,id=serial0 -mon chardev=serial0,mode=readline -serial chardev:serial0 \
	-net "nic,macaddr=52:54:00:28:cb:96,model=virtio" \
        -net user \
	-vnc :1 \
	-fsdev local,security_model=none,id=fsdev0,path="$PWD" -device virtio-9p-pci,id=fs0,fsdev=fsdev0,mount_tag=build-srcdir \
	-smbios type=11,value=io.systemd.credential:passwd.plaintext-password.root=12345 \
	-snapshot "$@"

	#-smbios type=11,value=io.systemd.credential:passwd.hashed-password.root='$y$j9T$EPXPqkgv/G.I4n2sKzbl3.$9X6WvkGgEFsKoxz2.tThZGArKayvKw0uiF8qJXIjGd1'
	#-fw_cfg name=opt/io.systemd.credentials/passwd.hashed-password.root,string='$y$j9T$EPXPqkgv/G.I4n2sKzbl3.$9X6WvkGgEFsKoxz2.tThZGArKayvKw0uiF8qJXIjGd1'
	#-smbios type=11,value=io.systemd.credential:passwd.hashed-password.root='$y$j9T$EPXPqkgv/G.I4n2sKzbl3.$9X6WvkGgEFsKoxz2.tThZGArKayvKw0uiF8qJXIjGd1' \
